  - name: Copy config   
    template:
      src: vsftpd.conf.j2
      dest: /etc/vsftpd/vsftpd.conf
      owner: root
      group: root
      mode: 0644
    notify:
      - restart vsftpd
      
  - name: Adding nologin shell
    lineinfile:
      state: present
      dest: /etc/shells
      line: "/usr/sbin/nologin"
      regexp: "^/usr/sbin/nologin"
      insertafter: EOF

  - name: Setting SELinux booleans
    seboolean:
      name: "{{ item.key }}"
      state: "{{ item.value }}"
    with_dict: "{{ vsftpd_seboolean }}"